apiVersion: v1
kind: Namespace
metadata:
  name: alliance
  labels:
    name: alliance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-wing-red
  namespace: alliance
spec:
  selector:
    matchLabels:
      name: x-wing-red
  replicas: 3
  template:
    metadata:
      labels:
        name: x-wing-red
    spec:
      containers:
      - name: x-wing-red
        image: docker.io/cilium/json-mock:1.0
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c", "while true; do curl -sS -o /dev/null docking-doors.empire.svc.cluster.local; sleep $(( ( RANDOM % 10 )  + 1 )); done"]
---
apiVersion: v1
kind: Service
metadata:
  name: communications-service
  namespace: alliance
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    name: communications-station
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: communications-station
  namespace: alliance
spec:
  selector:
    matchLabels:
      name: communications-station
  replicas: 1
  template:
    metadata:
      labels:
        name: communications-station
    spec:
      containers:
      - name: communications-station
        image: docker.io/cilium/json-mock:1.0
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command: ["curl", "-sS", "-o", "/dev/null", "localhost"]
        livenessProbe:
          exec:
            command: ["curl", "-sS", "-o", "/dev/null", "localhost"]
          periodSeconds: 3
          successThreshold: 1
          failureThreshold: 2
